// fetch all items
export const FETCH_ALL_ITEMS_REQUEST = "FETCH_ALL_ITEMS_REQUEST";
export const FETCH_ALL_ITEMS_SUCCESS = "FETCH_ALL_ITEMS_SUCCESS";
export const FETCH_ALL_ITEMS_FAILURE = "FETCH_ALL_ITEMS_FAILURE";

// fetch single item
export const FETCH_SINGLE_ITEM_REQUEST = "FETCH_SINGLE_ITEM_REQUEST";
export const FETCH_SINGLE_ITEM_SUCCESS = "FETCH_SINGLE_ITEM_SUCCESS";
export const FETCH_SINGLE_ITEM_FAILURE = "FETCH_SINGLE_ITEM_FAILURE";
export const REMOVE_SINGLE_ITEM = "REMOVE_SINGLE_ITEM";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE";
export const INSERT_ITEM_SUCCESS = "INSERT_ITEM_SUCCESS";
export const INSERT_ITEM_FAILURE = "INSERT_ITEM_FAILURE";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE";
export const INCREMENT_DECREMENT_STOCK_REQUEST =
  "INCREMENT_DECREMENT_STOCK_REQUEST";
export const INCREMENT_DECREMENT_STOCK_SUCCESS =
  "INCREMENT_DECREMENT_STOCK_SUCCESS";
export const INCREMENT_DECREMENT_STOCK_FAILURE =
  "INCREMENT_DECREMENT_STOCK_FAILURE";
export const SHOW_TOAST = "SHOW_TOAST";

//AUTH

export const SIGNUP_USER = "SIGNUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const REMOVE_USER = "REMOVE_USER";
export const RESET_ITEMS = "RESET_ITEMS";
